
GET http://localhost:5052

###

GET http://localhost:5052/api/categories

###

POST http://localhost:5052/api/categories
Content-Type: application/json

{
    "name" : "Electronics",
    "description" : "Devices and gadgets including phones, laptops, and other electronic equipment"
}

### 

PUT http://localhost:5052/api/categories

### 

DELETE http://localhost:5052/api/categories