
GET http://localhost:5027/api/categories

###

GET http://localhost:5027/api/categories?searchValue=Electronics

###

POST http://localhost:5027/api/categories
Content-Type: application/json

{
    "name" : "electronics",  
    "description" : "Devices and gadgets including phones, laptops, and other electronic equipment"
}

### 

PUT http://localhost:5027/api/categories/20fe4e68-c97b-4d59-a935-bf559e246add
Content-Type: application/json

{
   // "name" : "Eletronic device",
   ///  "description" : "Devices and gadgets including phones, laptops, and other electronic equipment"
  // "name" : "",
  // "description" : ""
}

### 

DELETE http://localhost:5027/api/categories/ff5b785e-fa76-4237-bec6-6d54b1a780c5