
GET http://localhost:5052

###

GET http://localhost:5052/api/categories?searchValue = "Electronics"

###

POST http://localhost:5052/api/categories
Content-Type: application/json

{
    "name" : "Electoric",
    "description" : "Devices and gadgets including phones, laptops, and other electronic equipment"
}

### 

PUT http://localhost:5052/api/categories/a82919e0-9ee2-45e4-854f-4c50e05afc46
Content-Type: application/json

{
    "name" : "Eletronic device",
    "description" : "Devices and gadgets including phones, laptops, and other electronic equipment"
}

### 

DELETE http://localhost:5052/api/categories